<?php
/**
 * SalesChannelDomainRelationships
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Rundum\Shopware6\Model;

use \ArrayAccess;
use \Rundum\Shopware6\ObjectSerializer;

/**
 * SalesChannelDomainRelationships Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SalesChannelDomainRelationships implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'sales_channel_domain_relationships';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sales_channel' => '\Rundum\Shopware6\Model\SalesChannelDomainRelationshipsSalesChannel',
'language' => '\Rundum\Shopware6\Model\SalesChannelDomainRelationshipsLanguage',
'currency' => '\Rundum\Shopware6\Model\SalesChannelDomainRelationshipsCurrency',
'snippet_set' => '\Rundum\Shopware6\Model\SalesChannelDomainRelationshipsSnippetSet',
'sales_channel_default_hreflang' => '\Rundum\Shopware6\Model\SalesChannelDomainRelationshipsSalesChannelDefaultHreflang',
'product_exports' => '\Rundum\Shopware6\Model\SalesChannelDomainRelationshipsProductExports'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sales_channel' => null,
'language' => null,
'currency' => null,
'snippet_set' => null,
'sales_channel_default_hreflang' => null,
'product_exports' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sales_channel' => 'salesChannel',
'language' => 'language',
'currency' => 'currency',
'snippet_set' => 'snippetSet',
'sales_channel_default_hreflang' => 'salesChannelDefaultHreflang',
'product_exports' => 'productExports'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sales_channel' => 'setSalesChannel',
'language' => 'setLanguage',
'currency' => 'setCurrency',
'snippet_set' => 'setSnippetSet',
'sales_channel_default_hreflang' => 'setSalesChannelDefaultHreflang',
'product_exports' => 'setProductExports'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sales_channel' => 'getSalesChannel',
'language' => 'getLanguage',
'currency' => 'getCurrency',
'snippet_set' => 'getSnippetSet',
'sales_channel_default_hreflang' => 'getSalesChannelDefaultHreflang',
'product_exports' => 'getProductExports'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sales_channel'] = isset($data['sales_channel']) ? $data['sales_channel'] : null;
        $this->container['language'] = isset($data['language']) ? $data['language'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['snippet_set'] = isset($data['snippet_set']) ? $data['snippet_set'] : null;
        $this->container['sales_channel_default_hreflang'] = isset($data['sales_channel_default_hreflang']) ? $data['sales_channel_default_hreflang'] : null;
        $this->container['product_exports'] = isset($data['product_exports']) ? $data['product_exports'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sales_channel
     *
     * @return \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsSalesChannel
     */
    public function getSalesChannel()
    {
        return $this->container['sales_channel'];
    }

    /**
     * Sets sales_channel
     *
     * @param \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsSalesChannel $sales_channel sales_channel
     *
     * @return $this
     */
    public function setSalesChannel($sales_channel)
    {
        $this->container['sales_channel'] = $sales_channel;

        return $this;
    }

    /**
     * Gets language
     *
     * @return \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsLanguage
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsLanguage $language language
     *
     * @return $this
     */
    public function setLanguage($language)
    {
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsCurrency
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsCurrency $currency currency
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets snippet_set
     *
     * @return \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsSnippetSet
     */
    public function getSnippetSet()
    {
        return $this->container['snippet_set'];
    }

    /**
     * Sets snippet_set
     *
     * @param \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsSnippetSet $snippet_set snippet_set
     *
     * @return $this
     */
    public function setSnippetSet($snippet_set)
    {
        $this->container['snippet_set'] = $snippet_set;

        return $this;
    }

    /**
     * Gets sales_channel_default_hreflang
     *
     * @return \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsSalesChannelDefaultHreflang
     */
    public function getSalesChannelDefaultHreflang()
    {
        return $this->container['sales_channel_default_hreflang'];
    }

    /**
     * Sets sales_channel_default_hreflang
     *
     * @param \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsSalesChannelDefaultHreflang $sales_channel_default_hreflang sales_channel_default_hreflang
     *
     * @return $this
     */
    public function setSalesChannelDefaultHreflang($sales_channel_default_hreflang)
    {
        $this->container['sales_channel_default_hreflang'] = $sales_channel_default_hreflang;

        return $this;
    }

    /**
     * Gets product_exports
     *
     * @return \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsProductExports
     */
    public function getProductExports()
    {
        return $this->container['product_exports'];
    }

    /**
     * Sets product_exports
     *
     * @param \Rundum\Shopware6\Model\SalesChannelDomainRelationshipsProductExports $product_exports product_exports
     *
     * @return $this
     */
    public function setProductExports($product_exports)
    {
        $this->container['product_exports'] = $product_exports;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
