<?php
/**
 * CountryRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Rundum\Shopware6;

/**
 * CountryRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description CountryRelationships
 * @package     Rundum\Shopware6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CountryRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CountryRelationships"
     */
    public function testCountryRelationships()
    {
    }

    /**
     * Test attribute "states"
     */
    public function testPropertyStates()
    {
    }

    /**
     * Test attribute "customer_addresses"
     */
    public function testPropertyCustomerAddresses()
    {
    }

    /**
     * Test attribute "order_addresses"
     */
    public function testPropertyOrderAddresses()
    {
    }

    /**
     * Test attribute "sales_channel_default_assignments"
     */
    public function testPropertySalesChannelDefaultAssignments()
    {
    }

    /**
     * Test attribute "sales_channels"
     */
    public function testPropertySalesChannels()
    {
    }

    /**
     * Test attribute "tax_rules"
     */
    public function testPropertyTaxRules()
    {
    }
}
