<?php
/**
 * CustomerRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Rundum\Shopware6;

/**
 * CustomerRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerRelationships
 * @package     Rundum\Shopware6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerRelationships"
     */
    public function testCustomerRelationships()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "default_payment_method"
     */
    public function testPropertyDefaultPaymentMethod()
    {
    }

    /**
     * Test attribute "sales_channel"
     */
    public function testPropertySalesChannel()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "last_payment_method"
     */
    public function testPropertyLastPaymentMethod()
    {
    }

    /**
     * Test attribute "default_billing_address"
     */
    public function testPropertyDefaultBillingAddress()
    {
    }

    /**
     * Test attribute "default_shipping_address"
     */
    public function testPropertyDefaultShippingAddress()
    {
    }

    /**
     * Test attribute "salutation"
     */
    public function testPropertySalutation()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "order_customers"
     */
    public function testPropertyOrderCustomers()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "promotions"
     */
    public function testPropertyPromotions()
    {
    }

    /**
     * Test attribute "product_reviews"
     */
    public function testPropertyProductReviews()
    {
    }

    /**
     * Test attribute "recovery_customer"
     */
    public function testPropertyRecoveryCustomer()
    {
    }

    /**
     * Test attribute "requested_group"
     */
    public function testPropertyRequestedGroup()
    {
    }

    /**
     * Test attribute "bound_sales_channel"
     */
    public function testPropertyBoundSalesChannel()
    {
    }

    /**
     * Test attribute "wishlists"
     */
    public function testPropertyWishlists()
    {
    }
}
