<?php
/**
 * LanguageRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Rundum\Shopware6;

/**
 * LanguageRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description LanguageRelationships
 * @package     Rundum\Shopware6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LanguageRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LanguageRelationships"
     */
    public function testLanguageRelationships()
    {
    }

    /**
     * Test attribute "parent"
     */
    public function testPropertyParent()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "translation_code"
     */
    public function testPropertyTranslationCode()
    {
    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {
    }

    /**
     * Test attribute "sales_channels"
     */
    public function testPropertySalesChannels()
    {
    }

    /**
     * Test attribute "sales_channel_default_assignments"
     */
    public function testPropertySalesChannelDefaultAssignments()
    {
    }

    /**
     * Test attribute "sales_channel_domains"
     */
    public function testPropertySalesChannelDomains()
    {
    }

    /**
     * Test attribute "customers"
     */
    public function testPropertyCustomers()
    {
    }

    /**
     * Test attribute "newsletter_recipients"
     */
    public function testPropertyNewsletterRecipients()
    {
    }

    /**
     * Test attribute "orders"
     */
    public function testPropertyOrders()
    {
    }

    /**
     * Test attribute "product_search_keywords"
     */
    public function testPropertyProductSearchKeywords()
    {
    }

    /**
     * Test attribute "product_keyword_dictionaries"
     */
    public function testPropertyProductKeywordDictionaries()
    {
    }

    /**
     * Test attribute "product_reviews"
     */
    public function testPropertyProductReviews()
    {
    }
}
