<?php
/**
 * MediaFolderConfigurationMediaThumbnailSizeFlatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Rundum\Shopware6;

/**
 * MediaFolderConfigurationMediaThumbnailSizeFlatTest Class Doc Comment
 *
 * @category    Class
 * @description Added since version: 6.0.0.0
 * @package     Rundum\Shopware6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MediaFolderConfigurationMediaThumbnailSizeFlatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MediaFolderConfigurationMediaThumbnailSizeFlat"
     */
    public function testMediaFolderConfigurationMediaThumbnailSizeFlat()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "media_folder_configuration_id"
     */
    public function testPropertyMediaFolderConfigurationId()
    {
    }

    /**
     * Test attribute "media_thumbnail_size_id"
     */
    public function testPropertyMediaThumbnailSizeId()
    {
    }

    /**
     * Test attribute "media_folder_configuration"
     */
    public function testPropertyMediaFolderConfiguration()
    {
    }

    /**
     * Test attribute "media_thumbnail_size"
     */
    public function testPropertyMediaThumbnailSize()
    {
    }
}
