<?php
/**
 * OrderShippingCostsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Rundum\Shopware6;

/**
 * OrderShippingCostsTest Class Doc Comment
 *
 * @category    Class
 * @description OrderShippingCosts
 * @package     Rundum\Shopware6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderShippingCostsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderShippingCosts"
     */
    public function testOrderShippingCosts()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "calculated_taxes"
     */
    public function testPropertyCalculatedTaxes()
    {
    }

    /**
     * Test attribute "tax_rules"
     */
    public function testPropertyTaxRules()
    {
    }

    /**
     * Test attribute "reference_price"
     */
    public function testPropertyReferencePrice()
    {
    }

    /**
     * Test attribute "list_price"
     */
    public function testPropertyListPrice()
    {
    }
}
