<?php
/**
 * OrderPriceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Rundum\Shopware6;

/**
 * OrderPriceTest Class Doc Comment
 *
 * @category    Class
 * @description OrderPrice
 * @package     Rundum\Shopware6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderPriceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderPrice"
     */
    public function testOrderPrice()
    {
    }

    /**
     * Test attribute "net_price"
     */
    public function testPropertyNetPrice()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "calculated_taxes"
     */
    public function testPropertyCalculatedTaxes()
    {
    }

    /**
     * Test attribute "tax_rules"
     */
    public function testPropertyTaxRules()
    {
    }

    /**
     * Test attribute "position_price"
     */
    public function testPropertyPositionPrice()
    {
    }

    /**
     * Test attribute "tax_status"
     */
    public function testPropertyTaxStatus()
    {
    }
}
