<?php
/**
 * PromotionRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Rundum\Shopware6;

/**
 * PromotionRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description PromotionRelationships
 * @package     Rundum\Shopware6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PromotionRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PromotionRelationships"
     */
    public function testPromotionRelationships()
    {
    }

    /**
     * Test attribute "setgroups"
     */
    public function testPropertySetgroups()
    {
    }

    /**
     * Test attribute "sales_channels"
     */
    public function testPropertySalesChannels()
    {
    }

    /**
     * Test attribute "discounts"
     */
    public function testPropertyDiscounts()
    {
    }

    /**
     * Test attribute "individual_codes"
     */
    public function testPropertyIndividualCodes()
    {
    }

    /**
     * Test attribute "persona_rules"
     */
    public function testPropertyPersonaRules()
    {
    }

    /**
     * Test attribute "persona_customers"
     */
    public function testPropertyPersonaCustomers()
    {
    }

    /**
     * Test attribute "order_rules"
     */
    public function testPropertyOrderRules()
    {
    }

    /**
     * Test attribute "cart_rules"
     */
    public function testPropertyCartRules()
    {
    }
}
