<?php
/**
 * StateMachineTransitionRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Rundum\Shopware6;

/**
 * StateMachineTransitionRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description StateMachineTransitionRelationships
 * @package     Rundum\Shopware6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StateMachineTransitionRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StateMachineTransitionRelationships"
     */
    public function testStateMachineTransitionRelationships()
    {
    }

    /**
     * Test attribute "state_machine"
     */
    public function testPropertyStateMachine()
    {
    }

    /**
     * Test attribute "from_state_machine_state"
     */
    public function testPropertyFromStateMachineState()
    {
    }

    /**
     * Test attribute "to_state_machine_state"
     */
    public function testPropertyToStateMachineState()
    {
    }
}
