<?php
/**
 * CustomerWishlistProductApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * CustomerWishlistProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerWishlistProductApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCustomerWishlistProduct
     *
     * Create a new Customer Wishlist Product resources.
     *
     */
    public function testCreateCustomerWishlistProduct()
    {
    }

    /**
     * Test case for deleteCustomerWishlistProduct
     *
     * Delete a Customer Wishlist Product resource.
     *
     */
    public function testDeleteCustomerWishlistProduct()
    {
    }

    /**
     * Test case for getCustomerWishlistProduct
     *
     * Detailed information about a Customer Wishlist Product resource.
     *
     */
    public function testGetCustomerWishlistProduct()
    {
    }

    /**
     * Test case for getCustomerWishlistProductList
     *
     * List with basic information of Customer Wishlist Product resources.
     *
     */
    public function testGetCustomerWishlistProductList()
    {
    }

    /**
     * Test case for updateCustomerWishlistProduct
     *
     * Partially update information about a Customer Wishlist Product resource.
     *
     */
    public function testUpdateCustomerWishlistProduct()
    {
    }
}
