<?php
/**
 * DeadMessageApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * DeadMessageApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DeadMessageApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createDeadMessage
     *
     * Create a new Dead Message resources.
     *
     */
    public function testCreateDeadMessage()
    {
    }

    /**
     * Test case for deleteDeadMessage
     *
     * Delete a Dead Message resource.
     *
     */
    public function testDeleteDeadMessage()
    {
    }

    /**
     * Test case for getDeadMessage
     *
     * Detailed information about a Dead Message resource.
     *
     */
    public function testGetDeadMessage()
    {
    }

    /**
     * Test case for getDeadMessageList
     *
     * List with basic information of Dead Message resources.
     *
     */
    public function testGetDeadMessageList()
    {
    }

    /**
     * Test case for updateDeadMessage
     *
     * Partially update information about a Dead Message resource.
     *
     */
    public function testUpdateDeadMessage()
    {
    }
}
