<?php
/**
 * DocumentBaseConfigSalesChannelApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * DocumentBaseConfigSalesChannelApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentBaseConfigSalesChannelApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createDocumentBaseConfigSalesChannel
     *
     * Create a new Document Base Config Sales Channel resources.
     *
     */
    public function testCreateDocumentBaseConfigSalesChannel()
    {
    }

    /**
     * Test case for deleteDocumentBaseConfigSalesChannel
     *
     * Delete a Document Base Config Sales Channel resource.
     *
     */
    public function testDeleteDocumentBaseConfigSalesChannel()
    {
    }

    /**
     * Test case for getDocumentBaseConfigSalesChannel
     *
     * Detailed information about a Document Base Config Sales Channel resource.
     *
     */
    public function testGetDocumentBaseConfigSalesChannel()
    {
    }

    /**
     * Test case for getDocumentBaseConfigSalesChannelList
     *
     * List with basic information of Document Base Config Sales Channel resources.
     *
     */
    public function testGetDocumentBaseConfigSalesChannelList()
    {
    }

    /**
     * Test case for updateDocumentBaseConfigSalesChannel
     *
     * Partially update information about a Document Base Config Sales Channel resource.
     *
     */
    public function testUpdateDocumentBaseConfigSalesChannel()
    {
    }
}
