<?php
/**
 * MediaDefaultFolderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * MediaDefaultFolderApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MediaDefaultFolderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMediaDefaultFolder
     *
     * Create a new Media Default Folder resources.
     *
     */
    public function testCreateMediaDefaultFolder()
    {
    }

    /**
     * Test case for deleteMediaDefaultFolder
     *
     * Delete a Media Default Folder resource.
     *
     */
    public function testDeleteMediaDefaultFolder()
    {
    }

    /**
     * Test case for getMediaDefaultFolder
     *
     * Detailed information about a Media Default Folder resource.
     *
     */
    public function testGetMediaDefaultFolder()
    {
    }

    /**
     * Test case for getMediaDefaultFolderList
     *
     * List with basic information of Media Default Folder resources.
     *
     */
    public function testGetMediaDefaultFolderList()
    {
    }

    /**
     * Test case for updateMediaDefaultFolder
     *
     * Partially update information about a Media Default Folder resource.
     *
     */
    public function testUpdateMediaDefaultFolder()
    {
    }
}
