<?php
/**
 * MediaThumbnailApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * MediaThumbnailApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MediaThumbnailApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMediaThumbnail
     *
     * Create a new Media Thumbnail resources.
     *
     */
    public function testCreateMediaThumbnail()
    {
    }

    /**
     * Test case for deleteMediaThumbnail
     *
     * Delete a Media Thumbnail resource.
     *
     */
    public function testDeleteMediaThumbnail()
    {
    }

    /**
     * Test case for getMediaThumbnail
     *
     * Detailed information about a Media Thumbnail resource.
     *
     */
    public function testGetMediaThumbnail()
    {
    }

    /**
     * Test case for getMediaThumbnailList
     *
     * List with basic information of Media Thumbnail resources.
     *
     */
    public function testGetMediaThumbnailList()
    {
    }

    /**
     * Test case for updateMediaThumbnail
     *
     * Partially update information about a Media Thumbnail resource.
     *
     */
    public function testUpdateMediaThumbnail()
    {
    }
}
