<?php
/**
 * MediaFolderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * MediaFolderApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MediaFolderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMediaFolder
     *
     * Create a new Media Folder resources.
     *
     */
    public function testCreateMediaFolder()
    {
    }

    /**
     * Test case for deleteMediaFolder
     *
     * Delete a Media Folder resource.
     *
     */
    public function testDeleteMediaFolder()
    {
    }

    /**
     * Test case for getMediaFolder
     *
     * Detailed information about a Media Folder resource.
     *
     */
    public function testGetMediaFolder()
    {
    }

    /**
     * Test case for getMediaFolderList
     *
     * List with basic information of Media Folder resources.
     *
     */
    public function testGetMediaFolderList()
    {
    }

    /**
     * Test case for updateMediaFolder
     *
     * Partially update information about a Media Folder resource.
     *
     */
    public function testUpdateMediaFolder()
    {
    }
}
