<?php
/**
 * NumberRangeStateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * NumberRangeStateApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NumberRangeStateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNumberRangeState
     *
     * Create a new Number Range State resources.
     *
     */
    public function testCreateNumberRangeState()
    {
    }

    /**
     * Test case for deleteNumberRangeState
     *
     * Delete a Number Range State resource.
     *
     */
    public function testDeleteNumberRangeState()
    {
    }

    /**
     * Test case for getNumberRangeState
     *
     * Detailed information about a Number Range State resource.
     *
     */
    public function testGetNumberRangeState()
    {
    }

    /**
     * Test case for getNumberRangeStateList
     *
     * List with basic information of Number Range State resources.
     *
     */
    public function testGetNumberRangeStateList()
    {
    }

    /**
     * Test case for updateNumberRangeState
     *
     * Partially update information about a Number Range State resource.
     *
     */
    public function testUpdateNumberRangeState()
    {
    }
}
