<?php
/**
 * PluginApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * PluginApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PluginApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPlugin
     *
     * Create a new Plugin resources.
     *
     */
    public function testCreatePlugin()
    {
    }

    /**
     * Test case for deletePlugin
     *
     * Delete a Plugin resource.
     *
     */
    public function testDeletePlugin()
    {
    }

    /**
     * Test case for getPlugin
     *
     * Detailed information about a Plugin resource.
     *
     */
    public function testGetPlugin()
    {
    }

    /**
     * Test case for getPluginList
     *
     * List with basic information of Plugin resources.
     *
     */
    public function testGetPluginList()
    {
    }

    /**
     * Test case for updatePlugin
     *
     * Partially update information about a Plugin resource.
     *
     */
    public function testUpdatePlugin()
    {
    }
}
