<?php
/**
 * ProductSortingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * ProductSortingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductSortingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createProductSorting
     *
     * Create a new Product Sorting resources.
     *
     */
    public function testCreateProductSorting()
    {
    }

    /**
     * Test case for deleteProductSorting
     *
     * Delete a Product Sorting resource.
     *
     */
    public function testDeleteProductSorting()
    {
    }

    /**
     * Test case for getProductSorting
     *
     * Detailed information about a Product Sorting resource.
     *
     */
    public function testGetProductSorting()
    {
    }

    /**
     * Test case for getProductSortingList
     *
     * List with basic information of Product Sorting resources.
     *
     */
    public function testGetProductSortingList()
    {
    }

    /**
     * Test case for updateProductSorting
     *
     * Partially update information about a Product Sorting resource.
     *
     */
    public function testUpdateProductSorting()
    {
    }
}
