<?php
/**
 * PromotionDiscountPricesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * PromotionDiscountPricesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PromotionDiscountPricesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPromotionDiscountPrices
     *
     * Create a new Promotion Discount Prices resources.
     *
     */
    public function testCreatePromotionDiscountPrices()
    {
    }

    /**
     * Test case for deletePromotionDiscountPrices
     *
     * Delete a Promotion Discount Prices resource.
     *
     */
    public function testDeletePromotionDiscountPrices()
    {
    }

    /**
     * Test case for getPromotionDiscountPrices
     *
     * Detailed information about a Promotion Discount Prices resource.
     *
     */
    public function testGetPromotionDiscountPrices()
    {
    }

    /**
     * Test case for getPromotionDiscountPricesList
     *
     * List with basic information of Promotion Discount Prices resources.
     *
     */
    public function testGetPromotionDiscountPricesList()
    {
    }

    /**
     * Test case for updatePromotionDiscountPrices
     *
     * Partially update information about a Promotion Discount Prices resource.
     *
     */
    public function testUpdatePromotionDiscountPrices()
    {
    }
}
