<?php
/**
 * StateMachineStateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rundum\Shopware6;

use Rundum\Shopware6\Configuration;
use Rundum\Shopware6\ApiException;
use Rundum\Shopware6\ObjectSerializer;

/**
 * StateMachineStateApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rundum\Shopware6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StateMachineStateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createStateMachineState
     *
     * Create a new State Machine State resources.
     *
     */
    public function testCreateStateMachineState()
    {
    }

    /**
     * Test case for deleteStateMachineState
     *
     * Delete a State Machine State resource.
     *
     */
    public function testDeleteStateMachineState()
    {
    }

    /**
     * Test case for getStateMachineState
     *
     * Detailed information about a State Machine State resource.
     *
     */
    public function testGetStateMachineState()
    {
    }

    /**
     * Test case for getStateMachineStateList
     *
     * List with basic information of State Machine State resources.
     *
     */
    public function testGetStateMachineStateList()
    {
    }

    /**
     * Test case for updateStateMachineState
     *
     * Partially update information about a State Machine State resource.
     *
     */
    public function testUpdateStateMachineState()
    {
    }
}
